runtime: nodejs14
instance_class: F2
entrypoint: node index.js  # Substitua 'app.js' pelo nome do arquivo principal do seu aplicativo

env_variables:
  PORT: 8080  # Porta em que o seu aplicativo Express irá escutar
